name: Release Node.js app

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - 
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ format('{}/node-app-github-actions-tutorial', secrets.DOCKERHUB_USERNAME) }}
